const {
  ACCESS_TOKEN_SECRET_KEY = "4218912025",
  ACCESS_TOKEN_EXPIRES_IN = "10m",
  REFRESH_TOKEN_SECRET_KEY = "4374293770",
  REFRESH_TOKEN_EXPIRES_IN = "24h",
  ENABLE_DOCUMENTATION = "false",
  TIME_CAPSULE_BASE_URL = "http://localhost:8000",
  TIME_CAPSULE_MAILER_USER,
  TIME_CAPSULE_MAILER_CLIENT_ID,
  TIME_CAPSULE_MAILER_CLIENT_SECRET,
  TIME_CAPSULE_MAILER_REDIRECT_URI,
  TIME_CAPSULE_MAILER_REFRESH_TOKEN,
} = process.env;

module.exports = {
  TIME_CAPSULE_BASE_URL,
  TIME_CAPSULE_MAILER_USER,
  TIME_CAPSULE_MAILER_CLIENT_ID,
  TIME_CAPSULE_MAILER_CLIENT_SECRET,
  TIME_CAPSULE_MAILER_REDIRECT_URI,
  TIME_CAPSULE_MAILER_REFRESH_TOKEN,
  ENABLE_DOCUMENTATION: ENABLE_DOCUMENTATION === "true",
  ACCESS_TOKEN_SECRET_KEY,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_SECRET_KEY,
  REFRESH_TOKEN_EXPIRES_IN,
};
